### Import des librairies utiles pour ce projet

In [433]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.express as px
import statsmodels.api as sm

### Chargement du dataset selon les csv remis lors de la mission

In [434]:
clients = pd.read_csv(r'..\projet9_Lapage\data\raw\customers.csv',sep=';', encoding='utf-8')
produits = pd.read_csv(r'..\projet9_Lapage\data\raw\products.csv',sep=';', encoding='utf-8')
transactions = pd.read_csv(r'..\projet9_Lapage\data\raw\Transactions.csv',sep=';', encoding='utf-8')

C:\Users\julie\AppData\Local\Temp\ipykernel_38068\591950576.py:3: DtypeWarning: Columns (0,1,2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  transactions = pd.read_csv(r'..\projet9_Lapage\data\raw\Transactions.csv',sep=';', encoding='utf-8')

### Dimensionnement du dataset

In [435]:
# Dataframe clients
clients.info()
clients.head()
clients.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8621 entries, 0 to 8620
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  8621 non-null   object
 1   sex        8621 non-null   object
 2   birth      8621 non-null   int64
dtypes: int64(1), object(2)
memory usage: 202.2+ KB

             birth
count  8621.000000
mean   1978.275606
std      16.917958
min    1929.000000
25%    1966.000000
50%    1979.000000
75%    1992.000000
max    2004.000000

In [436]:
# nombres de valeurs 'clients_id' uniques 
clients['client_id'].nunique()

8621

In [437]:
# nombres de valeurs 'sex' uniques 
clients['sex'].nunique()

2

In [438]:
# nombres de valeurs 'birth' uniques 
clients['birth'].nunique()

76

In [439]:
# Dataframe produits
produits.info()
produits.head()
produits.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id_prod  3286 non-null   object
 1   price    3286 non-null   float64
 2   categ    3286 non-null   int64
dtypes: float64(1), int64(1), object(1)
memory usage: 77.1+ KB

             price        categ
count  3286.000000  3286.000000
mean     21.863597     0.370359
std      29.849786     0.615446
min       0.620000     0.000000
25%       6.990000     0.000000
50%      13.075000     0.000000
75%      22.990000     1.000000
max     300.000000     2.000000

In [440]:
# nombres de valeurs 'id_prod' uniques 
produits['id_prod'].nunique()

3286

In [441]:
# nombres de valeurs 'price' uniques 
produits['price'].nunique()

1454

In [442]:
# nombres de valeurs 'categ' uniques 
produits['categ'].nunique()

3

In [443]:
# Dataframe Transactions
transactions.info()
transactions.head()
transactions.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id_prod     687534 non-null  object
 1   date        687534 non-null  object
 2   session_id  687534 non-null  object
 3   client_id   687534 non-null  object
dtypes: object(4)
memory usage: 32.0+ MB

       id_prod                        date session_id client_id
count   687534                      687534     687534    687534
unique    3265                      687419     345505      8600
top      1_369  2021-10-13 17:05:59.572162   s_118668    c_1609
freq      2340                           2         14     25586

In [444]:
# nombres de valeurs 'id_prod' uniques 
transactions['id_prod'].nunique()

3265

In [445]:
# nombres de valeurs 'date' uniques 
transactions['date'].nunique()

687419

In [446]:
# nombres de valeurs 'client_id' uniques 
transactions['client_id'].nunique()

8600

In [447]:
# nombres de valeurs 'id_prod' uniques 
transactions['id_prod'].nunique()

3265

### Vérification des présences de NULL dans les fichiers

In [448]:
clients.isnull().sum()

client_id    0
sex          0
birth        0
dtype: int64

In [449]:
produits.isnull().sum()

id_prod    0
price      0
categ      0
dtype: int64

In [450]:
transactions.isnull().sum()

id_prod       361041
date          361041
session_id    361041
client_id     361041
dtype: int64

### Nettoyage des données NULL dans le fichier transactions

In [451]:
transactions=transactions.dropna()
transactions.isnull().sum()

id_prod       0
date          0
session_id    0
client_id     0
dtype: int64

### Vérification des doublons éventuels

In [452]:
clients.duplicated().sum()

np.int64(0)

In [453]:
produits.duplicated().sum()

np.int64(0)

In [454]:
transactions.duplicated().sum()

np.int64(0)

### Vérification des HEAD de chaque csv du dataset

In [455]:
display(clients.head()), display(produits.head()), display(transactions.head())

  client_id sex  birth
0    c_4410   f   1967
1    c_7839   f   1975
2    c_1699   f   1984
3    c_5961   f   1962
4    c_5320   m   1943

  id_prod  price  categ
0  0_1421  19.99      0
1  0_1368   5.13      0
2   0_731  17.99      0
3   1_587   4.99      1
4  0_1507   3.99      0

  id_prod                        date session_id client_id
0  0_1259  2021-03-01 00:01:07.843138        s_1     c_329
1  0_1390  2021-03-01 00:02:26.047414        s_2     c_664
2  0_1352  2021-03-01 00:02:38.311413        s_3     c_580
3  0_1458  2021-03-01 00:04:54.559692        s_4    c_7912
4  0_1358  2021-03-01 00:05:18.801198        s_5    c_2033

(None, None, None)

### Modification du format de la date du dataframe transactions

In [456]:
transactions['date'] = pd.to_datetime(transactions['date']).dt.date

In [457]:
transactions.info()
transactions.head()

<class 'pandas.core.frame.DataFrame'>
Index: 687534 entries, 0 to 687533
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id_prod     687534 non-null  object
 1   date        687534 non-null  object
 2   session_id  687534 non-null  object
 3   client_id   687534 non-null  object
dtypes: object(4)
memory usage: 26.2+ MB

  id_prod        date session_id client_id
0  0_1259  2021-03-01        s_1     c_329
1  0_1390  2021-03-01        s_2     c_664
2  0_1352  2021-03-01        s_3     c_580
3  0_1458  2021-03-01        s_4    c_7912
4  0_1358  2021-03-01        s_5    c_2033

In [458]:
produits['price'] = pd.to_numeric(produits['price'])
produits.head()
produits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id_prod  3286 non-null   object
 1   price    3286 non-null   float64
 2   categ    3286 non-null   int64
dtypes: float64(1), int64(1), object(1)
memory usage: 77.1+ KB

In [459]:
clients.isnull().sum()

client_id    0
sex          0
birth        0
dtype: int64