### Import des librairies utiles pour ce projet

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.express as px
import statsmodels.api as sm

In [4]:
import sys
sys.path.append('..\src')
from data_manager import inspection

ok, étape suivante

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\julie\AppData\Local\Temp\ipykernel_9840\2256840857.py:2: SyntaxWarning: invalid escape sequence '\s'
  sys.path.append('..\src')
C:\Users\julie\AppData\Local\Temp\ipykernel_9840\2256840857.py:2: SyntaxWarning: invalid escape sequence '\s'
  sys.path.append('..\src')

NameError: name 'clients' is not defined

### Chargement du dataset selon les csv remis lors de la mission

In [83]:
clients = pd.read_csv(r'..\..\projet9_Lapage\data\raw\customers.csv',sep=';', encoding='utf-8')
produits = pd.read_csv(r'..\..\projet9_Lapage\data\raw\products.csv',sep=';', encoding='utf-8')
transactions = pd.read_csv(r'..\..\projet9_Lapage\data\raw\Transactions.csv',sep=';', encoding='utf-8')

C:\Users\julie\AppData\Local\Temp\ipykernel_26200\179223179.py:3: DtypeWarning: Columns (0,1,2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  transactions = pd.read_csv(r'..\..\projet9_Lapage\data\raw\Transactions.csv',sep=';', encoding='utf-8')

### Dimensionnement du dataset

In [84]:
# DATASET CLIENTS
inspection(clients)

---------------------------------------------------------------------
INSPECTION DU DATAFRAME
---------------------------------------------------------------------

---------------------------------------------------------------------
Affichage de la structure du df (colonnes, lignes):
---------------------------------------------------------------------
nombre de lignes : 8621
nombre de colonnes : 3

---------------------------------------------------------------------
Noms des colonnes :
---------------------------------------------------------------------
Index(['client_id', 'sex', 'birth'], dtype='object')

---------------------------------------------------------------------
Affichage des principales informations statistiques des données du df :
---------------------------------------------------------------------
             birth
count  8621.000000
mean   1978.275606
std      16.917958
min    1929.000000
25%    1966.000000
50%    1979.000000
75%    1992.000000
max    2004.000000

---------------------------------------------------------------------
Types des données :
---------------------------------------------------------------------
client_id    object
sex          object
birth         int64
dtype: object

---------------------------------------------------------------------
Affichage du nombre de valeurs uniques (afin de définir ce qui pourrait représenter une PK / FK):
---------------------------------------------------------------------
client_id    8621
sex             2
birth          76
dtype: int64

---------------------------------------------------------------------
Affichage du nombre de valeurs manquantes :
---------------------------------------------------------------------
client_id    0
sex          0
birth        0
dtype: int64
Affichage du nombre de doublons :
---------------------------------------------------------------------
0

---------------------------------------------------------------------
Affichage des 5 premières lignes :
---------------------------------------------------------------------
  client_id sex  birth
0    c_4410   f   1967
1    c_7839   f   1975
2    c_1699   f   1984
3    c_5961   f   1962
4    c_5320   m   1943

---------------------------------------------------------------------
Colonnes pouvant constituer une clé primaire : ['client_id']

In [85]:
# DATASET PRODUITS
inspection(produits)

---------------------------------------------------------------------
INSPECTION DU DATAFRAME
---------------------------------------------------------------------

---------------------------------------------------------------------
Affichage de la structure du df (colonnes, lignes):
---------------------------------------------------------------------
nombre de lignes : 3286
nombre de colonnes : 3

---------------------------------------------------------------------
Noms des colonnes :
---------------------------------------------------------------------
Index(['id_prod', 'price', 'categ'], dtype='object')

---------------------------------------------------------------------
Affichage des principales informations statistiques des données du df :
---------------------------------------------------------------------
             price        categ
count  3286.000000  3286.000000
mean     21.863597     0.370359
std      29.849786     0.615446
min       0.620000     0.000000
25%       6.990000     0.000000
50%      13.075000     0.000000
75%      22.990000     1.000000
max     300.000000     2.000000

---------------------------------------------------------------------
Types des données :
---------------------------------------------------------------------
id_prod     object
price      float64
categ        int64
dtype: object

---------------------------------------------------------------------
Affichage du nombre de valeurs uniques (afin de définir ce qui pourrait représenter une PK / FK):
---------------------------------------------------------------------
id_prod    3286
price      1454
categ         3
dtype: int64

---------------------------------------------------------------------
Affichage du nombre de valeurs manquantes :
---------------------------------------------------------------------
id_prod    0
price      0
categ      0
dtype: int64
Affichage du nombre de doublons :
---------------------------------------------------------------------
0

---------------------------------------------------------------------
Affichage des 5 premières lignes :
---------------------------------------------------------------------
  id_prod  price  categ
0  0_1421  19.99      0
1  0_1368   5.13      0
2   0_731  17.99      0
3   1_587   4.99      1
4  0_1507   3.99      0

---------------------------------------------------------------------
Colonnes pouvant constituer une clé primaire : ['id_prod']

In [86]:
# DATASET TRANSACTIONS
inspection(transactions)

---------------------------------------------------------------------
INSPECTION DU DATAFRAME
---------------------------------------------------------------------

---------------------------------------------------------------------
Affichage de la structure du df (colonnes, lignes):
---------------------------------------------------------------------
nombre de lignes : 1048575
nombre de colonnes : 4

---------------------------------------------------------------------
Noms des colonnes :
---------------------------------------------------------------------
Index(['id_prod', 'date', 'session_id', 'client_id'], dtype='object')

---------------------------------------------------------------------
Affichage des principales informations statistiques des données du df :
---------------------------------------------------------------------
       id_prod                        date session_id client_id
count   687534                      687534     687534    687534
unique    3265                      687419     345505      8600
top      1_369  2021-10-13 17:05:59.572162   s_118668    c_1609
freq      2340                           2         14     25586

---------------------------------------------------------------------
Types des données :
---------------------------------------------------------------------
id_prod       object
date          object
session_id    object
client_id     object
dtype: object

---------------------------------------------------------------------
Affichage du nombre de valeurs uniques (afin de définir ce qui pourrait représenter une PK / FK):
---------------------------------------------------------------------
id_prod         3265
date          687419
session_id    345505
client_id       8600
dtype: int64

---------------------------------------------------------------------
Affichage du nombre de valeurs manquantes :
---------------------------------------------------------------------
id_prod       361041
date          361041
session_id    361041
client_id     361041
dtype: int64
Affichage du nombre de doublons :
---------------------------------------------------------------------
361040

---------------------------------------------------------------------
Affichage des 5 premières lignes :
---------------------------------------------------------------------
  id_prod                        date session_id client_id
0  0_1259  2021-03-01 00:01:07.843138        s_1     c_329
1  0_1390  2021-03-01 00:02:26.047414        s_2     c_664
2  0_1352  2021-03-01 00:02:38.311413        s_3     c_580
3  0_1458  2021-03-01 00:04:54.559692        s_4    c_7912
4  0_1358  2021-03-01 00:05:18.801198        s_5    c_2033

---------------------------------------------------------------------
Aucune colonne ne peut constituer une clé primaire en l'état.

### Nettoyage des données NULL dans le fichier transactions

In [87]:
transactions=transactions.dropna()
transactions.isnull().sum()

id_prod       0
date          0
session_id    0
client_id     0
dtype: int64

### Modification du format de la date du dataframe transactions

In [88]:
transactions['date'] = pd.to_datetime(transactions['date']).dt.floor('D')

In [89]:
transactions.info()
transactions.head()

<class 'pandas.core.frame.DataFrame'>
Index: 687534 entries, 0 to 687533
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id_prod     687534 non-null  object
 1   date        687534 non-null  datetime64[ns]
 2   session_id  687534 non-null  object
 3   client_id   687534 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 26.2+ MB

  id_prod       date session_id client_id
0  0_1259 2021-03-01        s_1     c_329
1  0_1390 2021-03-01        s_2     c_664
2  0_1352 2021-03-01        s_3     c_580
3  0_1458 2021-03-01        s_4    c_7912
4  0_1358 2021-03-01        s_5    c_2033

In [90]:
produits['price'] = pd.to_numeric(produits['price'])
produits.head()
produits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id_prod  3286 non-null   object
 1   price    3286 non-null   float64
 2   categ    3286 non-null   int64
dtypes: float64(1), int64(1), object(1)
memory usage: 77.1+ KB

In [91]:
clients.isnull().sum()

client_id    0
sex          0
birth        0
dtype: int64

### Jointure des csv et création d'un unique csv df_lapage

In [92]:
df_transactions_produits = transactions.merge(produits, on='id_prod', how='left')
df_transactions_produits.head()

  id_prod       date session_id client_id  price  categ
0  0_1259 2021-03-01        s_1     c_329  11.99      0
1  0_1390 2021-03-01        s_2     c_664  19.37      0
2  0_1352 2021-03-01        s_3     c_580   4.50      0
3  0_1458 2021-03-01        s_4    c_7912   6.55      0
4  0_1358 2021-03-01        s_5    c_2033  16.49      0

In [93]:
df_lapage = df_transactions_produits.merge(clients, on='client_id', how='left')
df_lapage.head()

  id_prod       date session_id client_id  price  categ sex  birth
0  0_1259 2021-03-01        s_1     c_329  11.99      0   f   1967
1  0_1390 2021-03-01        s_2     c_664  19.37      0   m   1960
2  0_1352 2021-03-01        s_3     c_580   4.50      0   m   1988
3  0_1458 2021-03-01        s_4    c_7912   6.55      0   f   1989
4  0_1358 2021-03-01        s_5    c_2033  16.49      0   f   1956

In [94]:
inspection(df_lapage)

---------------------------------------------------------------------
INSPECTION DU DATAFRAME
---------------------------------------------------------------------

---------------------------------------------------------------------
Affichage de la structure du df (colonnes, lignes):
---------------------------------------------------------------------
nombre de lignes : 687534
nombre de colonnes : 8

---------------------------------------------------------------------
Noms des colonnes :
---------------------------------------------------------------------
Index(['id_prod', 'date', 'session_id', 'client_id', 'price', 'categ', 'sex',
       'birth'],
      dtype='object')

---------------------------------------------------------------------
Affichage des principales informations statistiques des données du df :
---------------------------------------------------------------------
                                date          price          categ  \
count                         687534  687534.000000  687534.000000
mean   2022-03-01 09:22:26.987930880      17.493918       0.448789
min              2021-03-01 00:00:00       0.620000       0.000000
25%              2021-09-10 00:00:00       8.990000       0.000000
50%              2022-02-27 00:00:00      13.990000       0.000000
75%              2022-08-28 00:00:00      19.080000       1.000000
max              2023-02-28 00:00:00     300.000000       2.000000
std                              NaN      18.238337       0.594563

               birth
count  687534.000000
mean     1977.817391
min      1929.000000
25%      1970.000000
50%      1980.000000
75%      1987.000000
max      2004.000000
std        13.607935

---------------------------------------------------------------------
Types des données :
---------------------------------------------------------------------
id_prod               object
date          datetime64[ns]
session_id            object
client_id             object
price                float64
categ                  int64
sex                   object
birth                  int64
dtype: object

---------------------------------------------------------------------
Affichage du nombre de valeurs uniques (afin de définir ce qui pourrait représenter une PK / FK):
---------------------------------------------------------------------
id_prod         3265
date             730
session_id    345505
client_id       8600
price           1442
categ              3
sex                2
birth             76
dtype: int64

---------------------------------------------------------------------
Affichage du nombre de valeurs manquantes :
---------------------------------------------------------------------
id_prod       0
date          0
session_id    0
client_id     0
price         0
categ         0
sex           0
birth         0
dtype: int64
Affichage du nombre de doublons :
---------------------------------------------------------------------
848

---------------------------------------------------------------------
Affichage des 5 premières lignes :
---------------------------------------------------------------------
  id_prod       date session_id client_id  price  categ sex  birth
0  0_1259 2021-03-01        s_1     c_329  11.99      0   f   1967
1  0_1390 2021-03-01        s_2     c_664  19.37      0   m   1960
2  0_1352 2021-03-01        s_3     c_580   4.50      0   m   1988
3  0_1458 2021-03-01        s_4    c_7912   6.55      0   f   1989
4  0_1358 2021-03-01        s_5    c_2033  16.49      0   f   1956

---------------------------------------------------------------------
Aucune colonne ne peut constituer une clé primaire en l'état.

### EXPORT DU DF_LAPAGE EN CSV

In [95]:
df_lapage.to_csv(r'..\..\projet9_Lapage\data\processed\df_lapage.csv',sep=';', encoding='utf-8', index=False)